# Generated by Django 4.2 on 2024-12-20 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teams", "new_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="role",
            field=models.CharField(
                choices=[("Admin", "Admin"), ("Member", "Member")], max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="teams.team",
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelTable(
            name="team",
            table=None,
        ),
        migrations.AlterModelTable(
            name="teammember",
            table=None,
        ),
    ]
