# Generated by Django 4.2 on 2024-12-18 23:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_avatar_user_bio_user_github_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tagline",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="avatars/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "svg"]
                    )
                ],
            ),
        ),
    ]
