# Generated by Django 4.2 on 2024-12-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("job_title", models.CharField(max_length=100)),
                ("status", models.CharField(default="Pending", max_length=50)),
                ("applied_date", models.DateField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
