# Generated by Django 4.2 on 2024-12-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="application",
            options={"ordering": ["-applied_date"]},
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Interview", "Interview"),
                    ("Offer", "Offer"),
                    ("Rejected", "Rejected"),
                    ("Accepted", "Accepted"),
                    ("Withdrawn", "Withdrawn"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
