# Generated by Django 4.2 on 2024-12-17 02:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0003_alter_application_options_alter_application_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="application",
            options={"ordering": ["-date_applied"]},
        ),
        migrations.RenameField(
            model_name="application",
            old_name="applied_date",
            new_name="date_applied",
        ),
        migrations.RemoveField(
            model_name="application",
            name="company_name",
        ),
        migrations.AddField(
            model_name="application",
            name="company",
            field=models.CharField(default="Unknown Company", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="job_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="job_title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name="application",
            table="applications_application",
        ),
    ]
