# Generated by Django 4.2 on 2024-12-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0006_sync_existing_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="job_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
