# Generated by Django 4.2 on 2024-12-20 18:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0007_alter_application_job_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="date_applied",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
