# Generated by Django 4.2 on 2024-12-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0008_alter_application_date_applied"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
