# Generated by Django 4.2 on 2025-01-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("email_integration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobemail",
            name="application_status",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("interview", "Interview"),
                    ("rejected", "Rejected"),
                    ("offer", "Offer"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="jobemail",
            name="company_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="jobemail",
            name="job_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="jobemail",
            name="parsing_confidence",
            field=models.FloatField(default=0.0),
        ),
    ]
