# Generated by Django 4.2 on 2025-01-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "email_integration",
            "0002_jobemail_application_status_jobemail_company_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="jobemail",
            name="email_domain",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="jobemail",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("full-time", "Full Time"),
                    ("part-time", "Part Time"),
                    ("contract", "Contract"),
                    ("remote", "Remote"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="jobemail",
            name="key_requirements",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="jobemail",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="jobemail",
            name="salary_range",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name="jobemail",
            index=models.Index(
                fields=["job_title", "company_name"],
                name="job_emails_job_tit_9fbe7e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="jobemail",
            index=models.Index(
                fields=["application_status"], name="job_emails_applica_8ac83e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobemail",
            index=models.Index(
                fields=["received_date"], name="job_emails_receive_de22bd_idx"
            ),
        ),
    ]
